import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Asyahadah Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col">
          {/* Navbar di atas */}
          <Navbar />

          {/* Kontainer utama (Sidebar + Konten) */}
          <div className="flex flex-1 pt-16"> {/* Tambahkan padding atas agar tidak tertutup navbar */}
            <Sidebar />
            <main className="flex-1 p-6 bg-gray-100 overflow-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
